site:
  title: "Quarkus Architecture - Sitio Antora"
  start_page: "quarkus-architecture-hexagonal::index.adoc"
  url: "./site"
components:
  - name: quarkus-architecture-hexagonal
    version: 1.0.0
    title: "Quarkus Architecture Hexagonal"
    nav: modules/ROOT/nav.adoc
    start_page: modules/ROOT/pages/index.adoc

# Playbook básico para generar el sitio Antora
# Ejecutar: antora antora-playbook.yml
