# HTTP
quarkus.http.port=8080

# Datasource - Postgres
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/app
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.transactions=xa

quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.acquisition-timeout=10

# Kafka (Reactive Messaging)
kafka.bootstrap.servers=localhost:9092
#kafka.bootstrap.servers=redpanda:9092

# Outgoing producer (DomainEventPublisher -> orders-out)
mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders
mp.messaging.outgoing.orders-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.orders-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.orders-out.acks=1

# Metrics
quarkus.micrometer.export.prometheus.path=/q/metrics

#swaguer
quarkus.swagger-ui.path=swaggerui
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.info.title=Example API
%dev.mp.openapi.extensions.smallrye.info.title=Example API (development)


